x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "providers"
  POSTGRES_PASSWORD: "GY34G6TH@!3fghF45"
  POSTGRES_USER: "user"

x-pgadmin-environment: &x-pgadmin-environment
  PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  PGADMIN_DEFAULT_PASSWORD: admin
  PGADMIN_CONFIG_SERVER_MODE: 'False'
  PGADMIN_PORT: "5050"

x-redis-environment: &x-redis-environment
  REDIS_PASSWORD: "2gRTsdg244!#wvDTG8"
  REDIS_PORT: "6379"

x-kafka-environment: &x-kafka-environment
  EXPOSE_PORT: "9092"
  KAFKA_NODE_ID: 1
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT'
  KAFKA_ADVERTISED_LISTENERS: 'HOST://localhost:9092,DOCKER://broker:19092'
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
  KAFKA_LISTENERS: 'CONTROLLER://:29093,HOST://:9092,DOCKER://:19092'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'DOCKER'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
  KAFKA_NUM_PARTITIONS: 3
  # KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

x-kafka-ui-environment: &x-kafka-ui-environment
  SERVER_PORT: "9090"
  DYNAMIC_CONFIG_ENABLED: 'true'
  KAFKA_CLUSTERS_0_NAME: local
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:19092

x-providers-app-environment: &x-providers-app-environment
  # ENV
  APP_ENV: "production"
  # HTTP
  HTTP_PORT: "8080"
  # GRPC
  GRPC_PORT: "8082"
  GRPC_GATEWAY_PORT: "8083"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_URL: "postgres://user:GY34G6TH@!3fghF45@db:5432/providers"


services: 
  providers:
    container_name: providers
    build: 
      context: .
      dockerfile: ./build/package/providers/Dockerfile
    command: /main
    environment:
      <<: *x-providers-app-environment
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
      - "${GRPC_PORT:-8082}:${GRPC_PORT:-8082}"
      - "${GRPC_GATEWAY_PORT:-8083}:${GRPC_GATEWAY_PORT:-8083}"
    depends_on:
      - db
    networks:
      app_network:
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - providers_data:/var/lib/postgresql/data
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      app_network:
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      <<: *x-pgadmin-environment
    volumes:
       - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      app_network:
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:8.0
    environment:
      <<: *x-redis-environment
    # volumes:
    #   - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    networks:
      app_network:
    restart: unless-stopped
  broker:
    container_name: broker
    image: apache/kafka:3.9.1
    environment:
      <<: *x-kafka-environment
    # volumes:
    #   - kafka_data:/tmp/kafka-logs
    ports:
      - "${EXPOSE_PORT:-9092}:${EXPOSE_PORT:-9092}"
    networks:
      app_network:
    restart: unless-stopped
  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "${SERVER_PORT:-9090}:${SERVER_PORT:-9090}"
    environment:
      <<: *x-kafka-ui-environment
    depends_on:
      - broker
    networks:
      app_network:
    restart: unless-stopped



networks:
  app_network:
    external: false


volumes:
  providers_data:
  pgadmin_data:
  # redis_data:
  # kafka_data: