// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/providers/messages.proto

package providers

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderID    string                 `protobuf:"bytes,1,opt,name=provider_id,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_api_providers_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Provider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProviderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderID    string                 `protobuf:"bytes,1,opt,name=provider_id,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCreateRequest) Reset() {
	*x = ProviderCreateRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCreateRequest) ProtoMessage() {}

func (x *ProviderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCreateRequest.ProtoReflect.Descriptor instead.
func (*ProviderCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderCreateRequest) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *ProviderCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderID    string                 `protobuf:"bytes,1,opt,name=provider_id,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderCreateResponse) Reset() {
	*x = ProviderCreateResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCreateResponse) ProtoMessage() {}

func (x *ProviderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCreateResponse.ProtoReflect.Descriptor instead.
func (*ProviderCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderCreateResponse) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

type ProviderListAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderListAllRequest) Reset() {
	*x = ProviderListAllRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderListAllRequest) ProtoMessage() {}

func (x *ProviderListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderListAllRequest.ProtoReflect.Descriptor instead.
func (*ProviderListAllRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{3}
}

type ProviderListAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderListAllResponse) Reset() {
	*x = ProviderListAllResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderListAllResponse) ProtoMessage() {}

func (x *ProviderListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderListAllResponse.ProtoReflect.Descriptor instead.
func (*ProviderListAllResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderListAllResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderID    string                 `protobuf:"bytes,1,opt,name=provider_id,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderUpdateRequest) Reset() {
	*x = ProviderUpdateRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderUpdateRequest) ProtoMessage() {}

func (x *ProviderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProviderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderUpdateRequest) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *ProviderUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProviderUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderUpdateResponse) Reset() {
	*x = ProviderUpdateResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderUpdateResponse) ProtoMessage() {}

func (x *ProviderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProviderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderUpdateResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ProviderDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderID    string                 `protobuf:"bytes,1,opt,name=provider_id,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderDeleteRequest) Reset() {
	*x = ProviderDeleteRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDeleteRequest) ProtoMessage() {}

func (x *ProviderDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProviderDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderDeleteRequest) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

type ProviderDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderDeleteResponse) Reset() {
	*x = ProviderDeleteResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDeleteResponse) ProtoMessage() {}

func (x *ProviderDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProviderDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{8}
}

var File_api_providers_messages_proto protoreflect.FileDescriptor

const file_api_providers_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/providers/messages.proto\x12.github.com.classydevv.fulfillment.providers.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb8\x01\n" +
	"\bProvider\x12 \n" +
	"\vprovider_id\x18\x01 \x01(\tR\vprovider_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"\xab\x01\n" +
	"\x15ProviderCreateRequest\x12%\n" +
	"\vprovider_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vprovider_id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name:R\x92AO\n" +
	"M*\x15ProviderCreateRequest2\x1fCreates a new delivery provider\xd2\x01\vprovider_id\xd2\x01\x04name\"Y\n" +
	"\x16ProviderCreateResponse\x12 \n" +
	"\vprovider_id\x18\x01 \x01(\tR\vprovider_id:\x1d\x92A\x1a\n" +
	"\x18*\x16ProviderCreateResponse\"\x18\n" +
	"\x16ProviderListAllRequest\"q\n" +
	"\x17ProviderListAllResponse\x12V\n" +
	"\tproviders\x18\x01 \x03(\v28.github.com.classydevv.fulfillment.providers.v1.ProviderR\tproviders\"M\n" +
	"\x15ProviderUpdateRequest\x12 \n" +
	"\vprovider_id\x18\x01 \x01(\tR\vprovider_id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x16ProviderUpdateResponse\x12T\n" +
	"\bprovider\x18\x01 \x01(\v28.github.com.classydevv.fulfillment.providers.v1.ProviderR\bprovider\"9\n" +
	"\x15ProviderDeleteRequest\x12 \n" +
	"\vprovider_id\x18\x01 \x01(\tR\vprovider_id\"\x18\n" +
	"\x16ProviderDeleteResponseBBZ@github.com/classydevv/fulfillment/pkg/api/providers/v1;providersb\x06proto3"

var (
	file_api_providers_messages_proto_rawDescOnce sync.Once
	file_api_providers_messages_proto_rawDescData []byte
)

func file_api_providers_messages_proto_rawDescGZIP() []byte {
	file_api_providers_messages_proto_rawDescOnce.Do(func() {
		file_api_providers_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_providers_messages_proto_rawDesc), len(file_api_providers_messages_proto_rawDesc)))
	})
	return file_api_providers_messages_proto_rawDescData
}

var file_api_providers_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_providers_messages_proto_goTypes = []any{
	(*Provider)(nil),                // 0: github.com.classydevv.fulfillment.providers.v1.Provider
	(*ProviderCreateRequest)(nil),   // 1: github.com.classydevv.fulfillment.providers.v1.ProviderCreateRequest
	(*ProviderCreateResponse)(nil),  // 2: github.com.classydevv.fulfillment.providers.v1.ProviderCreateResponse
	(*ProviderListAllRequest)(nil),  // 3: github.com.classydevv.fulfillment.providers.v1.ProviderListAllRequest
	(*ProviderListAllResponse)(nil), // 4: github.com.classydevv.fulfillment.providers.v1.ProviderListAllResponse
	(*ProviderUpdateRequest)(nil),   // 5: github.com.classydevv.fulfillment.providers.v1.ProviderUpdateRequest
	(*ProviderUpdateResponse)(nil),  // 6: github.com.classydevv.fulfillment.providers.v1.ProviderUpdateResponse
	(*ProviderDeleteRequest)(nil),   // 7: github.com.classydevv.fulfillment.providers.v1.ProviderDeleteRequest
	(*ProviderDeleteResponse)(nil),  // 8: github.com.classydevv.fulfillment.providers.v1.ProviderDeleteResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_api_providers_messages_proto_depIdxs = []int32{
	9, // 0: github.com.classydevv.fulfillment.providers.v1.Provider.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: github.com.classydevv.fulfillment.providers.v1.Provider.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: github.com.classydevv.fulfillment.providers.v1.ProviderListAllResponse.providers:type_name -> github.com.classydevv.fulfillment.providers.v1.Provider
	0, // 3: github.com.classydevv.fulfillment.providers.v1.ProviderUpdateResponse.provider:type_name -> github.com.classydevv.fulfillment.providers.v1.Provider
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_providers_messages_proto_init() }
func file_api_providers_messages_proto_init() {
	if File_api_providers_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_providers_messages_proto_rawDesc), len(file_api_providers_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_providers_messages_proto_goTypes,
		DependencyIndexes: file_api_providers_messages_proto_depIdxs,
		MessageInfos:      file_api_providers_messages_proto_msgTypes,
	}.Build()
	File_api_providers_messages_proto = out.File
	file_api_providers_messages_proto_goTypes = nil
	file_api_providers_messages_proto_depIdxs = nil
}
