// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/providers/messages.proto

package providers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider - full provider model
type Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id - идентификатор провайдера
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // TODO id should be of type ProviderId
	// name - название провайдера
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_api_providers_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id - идентификатор провайдера
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name - название провайдера
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProviderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id - идентификатор провайдера
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProviderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAllProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllProvidersRequest) Reset() {
	*x = ListAllProvidersRequest{}
	mi := &file_api_providers_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllProvidersRequest) ProtoMessage() {}

func (x *ListAllProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListAllProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{3}
}

type ListAllProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllProvidersResponse) Reset() {
	*x = ListAllProvidersResponse{}
	mi := &file_api_providers_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllProvidersResponse) ProtoMessage() {}

func (x *ListAllProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_providers_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListAllProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_providers_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_api_providers_messages_proto protoreflect.FileDescriptor

const file_api_providers_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/providers/messages.proto\x12+github.com.classydevv.fulfillment.providers\".\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\x15CreateProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x16CreateProviderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ListAllProvidersRequest\"o\n" +
	"\x18ListAllProvidersResponse\x12S\n" +
	"\tproviders\x18\x01 \x03(\v25.github.com.classydevv.fulfillment.providers.ProviderR\tprovidersB5Z3github.com/classydevv/fulfillment/pkg/api/providersb\x06proto3"

var (
	file_api_providers_messages_proto_rawDescOnce sync.Once
	file_api_providers_messages_proto_rawDescData []byte
)

func file_api_providers_messages_proto_rawDescGZIP() []byte {
	file_api_providers_messages_proto_rawDescOnce.Do(func() {
		file_api_providers_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_providers_messages_proto_rawDesc), len(file_api_providers_messages_proto_rawDesc)))
	})
	return file_api_providers_messages_proto_rawDescData
}

var file_api_providers_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_providers_messages_proto_goTypes = []any{
	(*Provider)(nil),                 // 0: github.com.classydevv.fulfillment.providers.Provider
	(*CreateProviderRequest)(nil),    // 1: github.com.classydevv.fulfillment.providers.CreateProviderRequest
	(*CreateProviderResponse)(nil),   // 2: github.com.classydevv.fulfillment.providers.CreateProviderResponse
	(*ListAllProvidersRequest)(nil),  // 3: github.com.classydevv.fulfillment.providers.ListAllProvidersRequest
	(*ListAllProvidersResponse)(nil), // 4: github.com.classydevv.fulfillment.providers.ListAllProvidersResponse
}
var file_api_providers_messages_proto_depIdxs = []int32{
	0, // 0: github.com.classydevv.fulfillment.providers.ListAllProvidersResponse.providers:type_name -> github.com.classydevv.fulfillment.providers.Provider
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_providers_messages_proto_init() }
func file_api_providers_messages_proto_init() {
	if File_api_providers_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_providers_messages_proto_rawDesc), len(file_api_providers_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_providers_messages_proto_goTypes,
		DependencyIndexes: file_api_providers_messages_proto_depIdxs,
		MessageInfos:      file_api_providers_messages_proto_msgTypes,
	}.Build()
	File_api_providers_messages_proto = out.File
	file_api_providers_messages_proto_goTypes = nil
	file_api_providers_messages_proto_depIdxs = nil
}
