// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/providers/service.proto

package providers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_providers_service_proto protoreflect.FileDescriptor

const file_api_providers_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/providers/service.proto\x12+github.com.classydevv.fulfillment.providers\x1a\x1capi/providers/messages.proto2\xd4\x02\n" +
	"\x10ProvidersService\x12\x9b\x01\n" +
	"\x0eCreateProvider\x12B.github.com.classydevv.fulfillment.providers.CreateProviderRequest\x1aC.github.com.classydevv.fulfillment.providers.CreateProviderResponse\"\x00\x12\xa1\x01\n" +
	"\x10ListAllProviders\x12D.github.com.classydevv.fulfillment.providers.ListAllProvidersRequest\x1aE.github.com.classydevv.fulfillment.providers.ListAllProvidersResponse\"\x00B5Z3github.com/classydevv/fulfillment/pkg/api/providersb\x06proto3"

var file_api_providers_service_proto_goTypes = []any{
	(*CreateProviderRequest)(nil),    // 0: github.com.classydevv.fulfillment.providers.CreateProviderRequest
	(*ListAllProvidersRequest)(nil),  // 1: github.com.classydevv.fulfillment.providers.ListAllProvidersRequest
	(*CreateProviderResponse)(nil),   // 2: github.com.classydevv.fulfillment.providers.CreateProviderResponse
	(*ListAllProvidersResponse)(nil), // 3: github.com.classydevv.fulfillment.providers.ListAllProvidersResponse
}
var file_api_providers_service_proto_depIdxs = []int32{
	0, // 0: github.com.classydevv.fulfillment.providers.ProvidersService.CreateProvider:input_type -> github.com.classydevv.fulfillment.providers.CreateProviderRequest
	1, // 1: github.com.classydevv.fulfillment.providers.ProvidersService.ListAllProviders:input_type -> github.com.classydevv.fulfillment.providers.ListAllProvidersRequest
	2, // 2: github.com.classydevv.fulfillment.providers.ProvidersService.CreateProvider:output_type -> github.com.classydevv.fulfillment.providers.CreateProviderResponse
	3, // 3: github.com.classydevv.fulfillment.providers.ProvidersService.ListAllProviders:output_type -> github.com.classydevv.fulfillment.providers.ListAllProvidersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_providers_service_proto_init() }
func file_api_providers_service_proto_init() {
	if File_api_providers_service_proto != nil {
		return
	}
	file_api_providers_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_providers_service_proto_rawDesc), len(file_api_providers_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_providers_service_proto_goTypes,
		DependencyIndexes: file_api_providers_service_proto_depIdxs,
	}.Build()
	File_api_providers_service_proto = out.File
	file_api_providers_service_proto_goTypes = nil
	file_api_providers_service_proto_depIdxs = nil
}
