version: v1
name: buf.build/yourorg/myprotos
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
plugins:
  - local: protoc-gen-go
    out: pkg
    opt:
      - paths=source_relative
  - local: protoc-gen-go-grpc
    out: pkg
    opt:
      - paths=source_relative
  - local: protoc-gen-grpc-gateway
    out: pkg
    opt:
      - paths=source_relative
      - generate_unbound_methods=true
  - local: protoc-gen-openapiv2
    out: pkg
    opt:
      - generate_unbound_methods=true