// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/providers": {
            "get": {
                "description": "List all available providers registered in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "List all providers",
                "operationId": "providerListAll",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.providerEntityResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new delivery provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Create a new provider",
                "operationId": "providerCreate",
                "parameters": [
                    {
                        "description": "Provider create parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.providerCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.providerCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}": {
            "put": {
                "description": "Updates a delivery provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Update a provider",
                "operationId": "providerUpdate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provider update parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.providerUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.providerUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a delivery provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Delete a provider",
                "operationId": "providerDelete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.responseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.providerCreateRequest": {
            "type": "object",
            "required": [
                "name",
                "provider_id"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Купер"
                },
                "provider_id": {
                    "type": "string",
                    "example": "kuper"
                }
            }
        },
        "v1.providerCreateResponse": {
            "type": "object",
            "properties": {
                "provider_id": {
                    "type": "string",
                    "example": "kuper"
                }
            }
        },
        "v1.providerEntityResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-05-08T06:07:14.810915Z"
                },
                "name": {
                    "type": "string",
                    "example": "Купер"
                },
                "provider_id": {
                    "type": "string",
                    "example": "kuper"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-05-08T06:07:14.810915Z"
                }
            }
        },
        "v1.providerUpdateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Купер"
                }
            }
        },
        "v1.providerUpdateResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-05-08T06:07:14.810915Z"
                },
                "name": {
                    "type": "string",
                    "example": "Купер"
                },
                "provider_id": {
                    "type": "string",
                    "example": "kuper"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-05-08T06:07:14.810915Z"
                }
            }
        },
        "v1.responseError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Provider API",
	Description:      "Service to manager all provider related data: delivery zones and slots, pickup points, tariffs, etc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
